name: kdecrypt
description: Decrypts XMON log files.
version: 1.0.0
repository: https://github.com/bdev42/kdecrypt

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  pointycastle: ^3.7.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
